[build]
  command   = ""
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build]
    publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"