import Head from 'next/head'
import { SliceZone } from "@prismicio/react";
import Image from 'next/image'
import { createClient } from "../prismicio";
import { components } from "../slices/index";

import styles from '../styles/Home.module.css'

export default function Home({pages}) {
  console.log('--pages--', pages)
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs - Prismic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ejempo usando <a href="https://nextjs.org">Next.js!</a> y <a href="https://prismic.io">Prismic!</a>
        </h1>

        <div className={styles.grid}>
          <SliceZone slices={pages?.data?.slices} components={components} />

          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
           Dev 
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps(context) {
  const client = await createClient({ context });
  const pages = await client.getSingle("pages");
  // const header = await client.getSingle("Header");
  // const footer = await client.getSingle("footer");
  console.log('--pages--', pages)
  return {
    props: {
      pages
    },
  };
}