import Head from 'next/head'
import { SliceZone } from "@prismicio/react";
import Image from 'next/image'
import { createClient } from "../prismicio";
import { components } from "../slices/index";

import styles from '../styles/Home.module.css'

export default function Home({pages}) {
  // console.log('--pages--', pages)
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs - Prismic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ejempo usando <a href="https://nextjs.org">Next.js!</a> y <a href="https://prismic.io">Prismic!</a>
        </h1>

        <div className={styles.grid}>
          <SliceZone slices={pages?.data?.slices || null} components={components} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>Dev</span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps(context) {
  const client = await createClient({ context });
  const pages = await client.getSingle("pages");
  // const header = await client.getSingle("Header");
  // const footer = await client.getSingle("footer");
  console.log('--pages--', pages)
  return {
    props: {
      pages
    },
  };
}